import { Amplify } from 'aws-amplify';

// IMPORTANT:
// `amplify_outputs.json` is generated by `npx ampx sandbox` / `npx ampx deploy` and is typically gitignored.
// We want the app to still run locally without AWS configured, so we load it optionally.
//
// `import.meta.glob` returns an empty object when the file doesn't exist (no build-time error).
const outputModules = import.meta.glob('../../amplify_outputs.json', {
  eager: true,
}) as Record<string, { default: Record<string, any> }>;

const outputs = Object.values(outputModules)[0]?.default;

export const hasAmplifyOutputs = Boolean(outputs);

// Ensure Amplify is configured before any other Amplify modules are used.
if (outputs) {
  Amplify.configure(outputs);
} else {
  // Local/offline mode (no AWS backend). Cloud features should be gated behind VITE_ENABLE_CLOUD_SYNC=true.
  console.info(
    '[Amplify] amplify_outputs.json not found. Running in local/offline mode. To enable cloud features run `npm run amplify:sandbox`.'
  );
}
